### PR TITLE
DEVEXP-199: Error in geoserverLib.sjs

### PR DESCRIPTION
**Pull request by BillFarber**
The team has been unable to find any tests or external code that use the geoserverService.
Therefore, we are tagging the current develop commit (https://github.com/marklogic-community/marklogic-geo-data-services/releases/tag/pre-geoserverService-removal) and deleting this file.
If we find out that we want this service in the future, we can add it back in at that time with the proper testing.

### CODE REVIEW

**Comment by BillFarber** [comment]
All the tests in this project as well as koop-provider-marklogic, still pass.

**Review by rjrudin — APPROVED** [review]

**Comment by jkerr5** [comment]
This is for the geoserver integration: https://github.com/marklogic-community/marklogic-geotools-plugin

**Comment by jkerr5** [comment]
There should be tests in this project for it but apparently not. Please keep this service in the codebase and we can discuss the priority/need of maintaining.

**Comment by rjrudin** [comment]
Hey @jkerr5 - we have a tag in place - "pre-geoserverService-removal" - that still has the two modules in question. So it's trivial to pull back in based on priority, though we'd of course want to then invest in tests and docs to explain what it is.

**Comment by jkerr5** [comment]
Can we just leave them in for now as wouldn't want the next release to just not work at all with the geotools project.

**Pull request merged**
