### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by mfgumban**
Module/service changes:
- fixed an issue in where the service descriptor's URI wasn't getting retrieved from the index/cache (review change made at `src/main/ml-modules/ext/serviceModel.sjs`)

Test changes:
- refactored class hierarchy (made it a bit more manageable/cleaner)
- added tests for `modelService` and `geoSearchService` including its "save" function
- fixed previous failing test `testStddevAndVarUrltone` due to floating point variance; test now uses a range instead of an exact value
- fixed previous failing test `testPolygonWithin4`; created a new polygon (using https://geojsonlint.com) that is indeed smaller than the GKG object being used to test against (OBJECTID 3298)

### CODE REVIEW

**Comment by mfgumban** [comment]
Added new Gradle task `resetAndTest` that does the following:
- clear the content database
- run mlRedeploy
- load test data
- run all tests

Usage:
`./gradlew -PenvironmentName=test -Pconfirm=true resetAndTest`

**Review by tdiepenbrock — APPROVED** [review]
Looks good to me, all tests are passing.

**Review by jkerr5 — APPROVED** [review]
Looks good to me

**Comment by jkerr5** [comment]
@mfgumban ok to delete this branch?

**Comment by mfgumban** [comment]
Yup, branch deleted.

**Pull request merged**
