### PR TITLE
Geoserver merge from master

### PR DESCRIPTION
**Pull request by tdiepenbrock**
merging in changes to support the geoserver plugin.

### CODE REVIEW

**Comment by mfgumban** [comment]
I have a failing test `ServiceDescriptorArrayTest > testDataSourceWithSparqlAsRoot`:

Request:
```json
{
  "query": {
    "orderByFields": "OBJECTID ASC",
    "resultRecordCount": 5,
    "returnGeometry": true
  },
  "params": {
    "method": "query",
    "id": "DataSourceArrayExample",
    "layer": 8
  }
}
```

Response:
```json
{
  "errorResponse": {
    "statusCode": 500,
    "status": "Error handling request",
    "messageCode": "RESTAPI-SRVEXERR",
    "message": "SQL-NOCOLUMN: Column not found: DocId7060845361284923445"
  }
}
```

Ran using the command `./gradlew -PenvironmentName=test test --info --tests *testDataSourceWithSparqlAsRoot` and using **MarkLogic 10.0-5**.  Would this be related to the additions in `geoQueryService.sjs` starting at line 1051?

**Comment by tdiepenbrock** [comment]
Actually, line 1088 is the issue.  This line assumes that if there is no geometry source specified (column, xpath, etc) it will use an op.fragmentIdColumn(defaultDocId) to join in the document.  However, op.fragmentIdColumn() is only applicable for optic views, not sparql-based layers like this one.  

The test is structured such that an op.joinDoc() could be done on a document uri, passing in the DocId variable from the sparql query.  However, line 1088 obviously doesn't account for that possibility.  Basically line 1088 makes an assumption that isn't valid for sparql-based layers.  Recommend for sparql layers we add a docUriColumn property to the layer, which would be required for sparql-based views that want to use an xpath geometry extractor.  The code block containing line 1088 would need to look for that property for sparql-based layers.  If it falls into a situation where the sparql doesn't pull a document uri column AND doesn't specify a column that contains geometry, the xpath extractor would have to fail because the descriptor is effectively invalid.

**Comment by tdiepenbrock** [comment]
Suggest we allow the following "documentUriColumn" property in the layer->geometry.source property.  This seems to work with a corresponding piece of code to use this column, if it exists, in op.joinDoc() in geoQueryService.sjs:

"geometry": {
        "format": "geojson",
        "coordinateSystem": "wgs84",
        "source": {
          "documentUriColumn":"DocId",
          "xpath": "//geometry"
        }
      },

**Comment by tdiepenbrock** [comment]
Committed fix.  Only one failing test, which I believe is expected.

**Pull request merged**
